name: Build PBR

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: download cidr
      run: |
        wget --no-check-certificate -cqO- http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest | grep "apnic|CN|ipv4|" | awk -F'|' '{print $4"/"32-log($5)/log(2)}' >IPchnroute
        sha256sum IPchnroute | awk '{print$1}' >IPchnroute.sha256sum
        chmod +x ros-dpbr.sh
        ./ros-dpbr.sh
        
    - name: Commit
      run: |
        git config --global user.email jacyl4@gmail.com
        git config --global user.name jacyl4
        git init
        git add .
        git commit -am "Auto PBR"
        
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
