name: Build PBR

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: download cidr
      run: |
        wget --no-check-certificate -cqO- http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest | grep "apnic|CN|ipv4|" | awk -F'|' '{print $4"/"32-log($5)/log(2)}' >IPchnroute1
        wget --no-check-certificate -cqO- https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt >>IPchnroute2
        cat IPchnroute1 IPchnroute2 | sort | uniq >IPchnroute
        sha256sum IPchnroute | awk '{print$1}' >IPchnroute.sha256sum
        rm -rf IPchnroute1
        rm -rf IPchnroute2
        
        chmod +x ros-dpbr.sh
        ./ros-dpbr.sh

        chmod +x Domains_chnlist.sh.sh
        ./Domains_chnlist.sh.sh

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
